batch_size = 5
location='Data'
annotated_file='Annotation.csv'
embed_size = 500           # dimensionality of image and word embeddings
hidden_size = 500          # number of features in hidden state of the RNN decoder
num_epochs = 1             # number of training epochs (1 for testing)
print_every = 200          # determines window for printing average loss
train_len = 10
val_len = 2
num_epochs = 10
annotated_json='training_annotation.json'
word2idx_json = 'word2idx.json'
idx2word_json = 'idx2word.json'
vocab_file='vocab.csv''
relationship_json='relationship.json'
object1_object2_json='object1_object2.json'